### ISSUE TITLE
经纬度加密是如何实现的呢？

### ISSUE THREAD

**Issue by lanzeweie** [EaxMov/xixunyun-auto#24]

**Comment by lanzeweie** [comment]
新版习讯云现在需要对经纬度进行一个加密，才能让习讯云服务器成功收到签到信息。
如何加密？

**Comment by louhulin** [comment]
请问有解决方法了么，我用的前几天突然无法成功签到了，代码运行成功却无法签到。

**Comment by lanzeweie** [comment]
> 请问有解决方法了么，我用的前几天突然无法成功签到了，代码运行成功却无法签到。

解决办法就是我亲自重写了一个了  https://github.com/lanzeweie/xixunyun-b
